# Generated by Django 4.0 on 2024-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldinfo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
