# Generated by Django 4.0 on 2024-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fieldinfo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='picture_path',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='history',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Picture'), (1, 'Video')], default=0),
        ),
    ]
