# Generated by Django 4.0 on 2024-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_picture_path_history_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='maturity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
